version: '3.1'

services:

  db:
    image: postgres:11

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto_games

    volumes:
      - ./database:/var/lib/postgresql/data
    ports: 
      - 5432:5432
  
